import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import ClientLayout from "./ClientLayout";
import ClientChatbot from "@/components/ClientChatbot";
import { Toaster } from "react-hot-toast"; // 👈 import Toaster

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ClientLayout>{children}</ClientLayout>
        <Toaster position="top-center" /> {/* 👈 THÊM DÒNG NÀY */}
        <ClientChatbot />
      </body>
    </html>
  );
}
